### ISSUE TITLE
Recursive Grammars

### ISSUE THREAD

**Issue by regexident** [robrix/Madness#40]
So I was messing around with Madness and tried implementing a very rudimentary regex (as in "real" regex) parser using Madness:

	<expression> ::= <union> | <term>
	<union> ::= <term> '|' <expression>
	<term> ::= { <factor> }
	<factor> ::= <base> { '*' }
	<group> ::= '(' <expression> ')'
	<base> ::= <char> | '\' <char> | <group>

A crude translation to Madness would look like this I guess:

	let expression = union | term
	let union = term ++ ignore("|") ++ expression
	let term = factor *
	let factor = base ++ ignore("*") *
	let group = ignore("(") ++ expression ++ ignore(")")
	let base = any | ignore("\\") ++ any | group

The obvious first question that comes to mind (apart from hunting down left-recursions, etc) is:

> How does one define recursive grammars in Madness like the one seen above?

Obviously the compiler complained about unresolved identifiers. Just as I'd expect it to do in such a situation.

Would you mind to elaborate on this very briefly (or even add an example to the playground)?

**Comment by robrix** [comment]
Going to close this out now.
