### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by robrix** [robrix/Madness#47]
We don’t have any right now! It’s just pass/fail. That sucks.

**Comment by jspahrsummers** [comment]
The current lack of error reporting will hit [Carthage](https://github.com/Carthage/Carthage) pretty hard, because any deviation from OGDL syntax will result in the whole file failing to parse, without any indication as to why.

**Comment by robrix** [comment]
So, we need:

- the current [index](https://github.com/robrix/Madness/issues/68) of parsing at every point
- error [location data](https://github.com/robrix/Madness/issues/61) for the productions
- some way to [pretty-print](https://github.com/robrix/Madness/issues/46) subsets of the grammar
- as part of that, some map from individual parsers into `Printable` identifiers, such that
  - we can terminate recursive printing, and
  - the caller can produce human-readable strings explaining the use of the identifiers to their users
- a composite pattern `Error` type, to pass the errors back up the stack in an `Either` or `Result`
- nice combinations of `Error` for failed alternatives (e.g. “expected x or y”)
- heuristics as to which error(s) to present (these may belong to the caller, but they’ll probably be defined in terms of Madness’ primitives)

My intuition is that the latter is essentially the same problem as ambiguity, cf #69.
