### ISSUE TITLE
Convenience for separator-delimited sequences

### ISSUE THREAD

**Issue by robrix** [robrix/Madness#56]
It’s super easy to parse e.g. (element + terminator) sequences:

```swift
(x ++ %";")*
```

But it’s a bit obnoxious to parse separator-delimited ones:

```swift
x ++ (%"," ++ x)* --> { [ $0 ] + $1 }
```

That’s a common, useful pattern, so it should be convenient, e.g.:

```swift
join(%", ", x) // overloading `join` is semantically reasonable but a bit strange
x * %"," // not a big fan of overloading * like this, and I don’t want to add too many more operators
```

**Comment by bencochran** [comment]
`sepBy` and `sepBy1` added in 94b7985092b370d65768c627593e75c89255a76d

(as I discovered after writing what turned out to be the same implementation… yay confirmation)

**Comment by robrix** [comment]
Whoops! Good catch.
