### ISSUE TITLE
Repetition by closed intervals

### ISSUE THREAD

**Issue by robrix** [robrix/Madness#60]
```swift
x * 1...3
```

will often read more naturally than

```swift
x * 1..<4
```

**Comment by davidcairns** [comment]
If `x * 2..<2` means that it parses exactly two times, then what does `x * 2...2` mean? The same thing?

**Comment by robrix** [comment]
Hm, good point—we’re probably actually conflating things a bit. `for each in 2..<2 { println(each) }` won’t print at all, whereas using `2...2` will print `2`; in keeping with that, repetition by empty half-closed intervals should probably be an error.

**Comment by davidcairns** [comment]
Alright, changed the semantics for `..<`, and added support for `...`. Now, back to paying work!

**Comment by davidcairns** [comment]
Got the work in a merge request over here: https://github.com/robrix/Madness/pull/62

**Comment by robrix** [comment]
Fixed by #63.
