### ISSUE TITLE
Swift 2.0 support

### ISSUE THREAD

**Issue by DanielAsher** [robrix/Madness#96]
Are there any plans to update the project to swift 2.0?

cheers,

Daniel

**Comment by robrix** [comment]
It’ll happen sooner or later. I haven’t had a driving need for parsing lately or it’d be done already.

I’d be happy to accept a PR for this from a third party who needs it more urgently.

**Comment by DanielAsher** [comment]
Hi robrix!!

thanks for the response. A nice opportunity to say that I love your `Madness` !

I've already hacked together a little library - based on yours - but with `Swiftx` underneath and using swift-2.0's exception handling. `String` handling has change quite a lot too, so lots and lots of changes!

not really sure what I'm doing, but enjoying the ride...

you can take a look at how it's shaping up [here](https://github.com/DanielAsher/SwiftReferenceApp/blob/feature/swift-2.0/SwiftReferenceApp/Playgrounds/Swiftx.playground/Pages/Parser%20Combinators%20from%20Scratch.xcplaygroundpage/Contents.swift)
